/* Generated By:JJTree: Do not edit this line. ASTtarget.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hdlparser;

public
class ASTtarget extends SimpleNode {
  public ASTtarget(int id) {
    super(id);
  }

  public ASTtarget(HDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=520a5f9ea66b4ebf245f84ff9b8c7cdf (do not edit this line) */
