/* Generated By:JJTree: Do not edit this line. ASTzeroOrOne.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hdlparser;

public
class ASTzeroOrOne extends SimpleNode {
  public ASTzeroOrOne(int id) {
    super(id);
  }

  public ASTzeroOrOne(HDLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aabc1a1cde095b1087df614a9e94a8d0 (do not edit this line) */
