/* Generated By:JJTree&JavaCC: Do not edit this line. HDLParserConstants.java */
package hdlparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OP = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int REL_OP = 8;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int HEX_LIT = 10;
  /** RegularExpression Id. */
  int BIN_LIT = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int ID = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<token of kind 5>",
    "<OP>",
    "\"~\"",
    "<REL_OP>",
    "<NUM>",
    "<HEX_LIT>",
    "<BIN_LIT>",
    "<STRING>",
    "\"if\"",
    "\"{\"",
    "\"}\"",
    "\"else\"",
    "\"input\"",
    "\"output\"",
    "\"signal\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"label\"",
    "<ID>",
  };

}
