/* Generated By:JavaCC: Do not edit this line. HDLParserTreeConstants.java Version 5.0 */
package hdlparser;

public interface HDLParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTBLOCK = 1;
  public int JJTIF_STMT = 2;
  public int JJTELSE_IF_STMT = 3;
  public int JJTELSE_STMT = 4;
  public int JJTDECLARATION = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTTARGET = 7;
  public int JJTINDEX = 8;
  public int JJTEXPR = 9;
  public int JJTVOID = 10;
  public int JJTSUBEXPR = 11;
  public int JJTTERM = 12;
  public int JJTSUBTERM = 13;
  public int JJTID = 14;
  public int JJTNUMBER = 15;
  public int JJTHEX = 16;
  public int JJTBIN = 17;
  public int JJTSET_LABEL = 18;


  public String[] jjtNodeName = {
    "file",
    "block",
    "if_stmt",
    "else_if_stmt",
    "else_stmt",
    "declaration",
    "assignment",
    "target",
    "index",
    "expr",
    "void",
    "subexpr",
    "term",
    "subterm",
    "id",
    "number",
    "hex",
    "bin",
    "set_label",
  };
}
/* JavaCC - OriginalChecksum=c565de4d608af3e697c63657a54a8336 (do not edit this line) */
