/* Generated By:JJTree: Do not edit this line. ASTdefault_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package memparser;

public
class ASTdefault_stmt extends SimpleNode {
  public ASTdefault_stmt(int id) {
    super(id);
  }

  public ASTdefault_stmt(MemParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MemParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7d138a61ea926f8b2a36ef9b1d4dfe79 (do not edit this line) */
