/* Generated By:JJTree&JavaCC: Do not edit this line. MemParserConstants.java */
package memparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MemParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 6;
  /** RegularExpression Id. */
  int HEX_LIT = 7;
  /** RegularExpression Id. */
  int BIN_LIT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "<token of kind 5>",
    "<NUM>",
    "<HEX_LIT>",
    "<BIN_LIT>",
    "\"default\"",
    "\":\"",
    "\";\"",
    "\"!\"",
  };

}
