/* Generated By:JavaCC: Do not edit this line. MemParserTreeConstants.java Version 5.0 */
package memparser;

public interface MemParserTreeConstants
{
  public int JJTFILE = 0;
  public int JJTDEFAULT_STMT = 1;
  public int JJTADDR_STMT = 2;
  public int JJTNUMBER = 3;


  public String[] jjtNodeName = {
    "file",
    "default_stmt",
    "addr_stmt",
    "number",
  };
}
/* JavaCC - OriginalChecksum=0f4f527453bf3ba97806a04ee0ed414e (do not edit this line) */
